### ISSUE TITLE
[Bug] t.sentinel.import lacks json support

### ISSUE THREAD

**Issue by neteler** [mundialis/t.sentinel#10]
When importing Sentinel-2 scenes using GRASS GIS 7.9, the band names seem to be missing:

```
t.rast.list s2_raleigh@sentinel2
name|mapset|start_time|end_time
T17SPV_20210513T155819_B02_10m|sentinel2|2021-05-13 15:58:19|None
T17SPV_20210513T155819_B03_10m|sentinel2|2021-05-13 15:58:19|None
T17SPV_20210513T155819_B04_10m|sentinel2|2021-05-13 15:58:19|None
T17SPV_20210513T155819_B08_10m|sentinel2|2021-05-13 15:58:19|None
...

i.band T17SPV_20210513T155819_B02_10m operation=print
No band reference assigned to <T17SPV_20210513T155819_B02_10m>
```

I have been using the NC sample data set example from here:
https://grass.osgeo.org/grass7/manuals/addons/i.sentinel.coverage.html#use-retrieved-sentinel-2-scene-names-for-import

Apparently, i.sentinel.import.worker.py accepts `-j`:
https://github.com/mundialis/t.sentinel/blob/be9a79d8fdafef79ef4e3cc0743858ba84b8fee3/i.sentinel.import.worker/i.sentinel.import.worker.py#L185

while it is missing in t.sentinel.import.py and not "sent" to i.sentinel.import.worker:

https://github.com/mundialis/t.sentinel/blob/be9a79d8fdafef79ef4e3cc0743858ba84b8fee3/t.sentinel.import/t.sentinel.import.py#L427

Probably only the `-j` flag needs to be added in the code?

Maybe I am overlooking something...

**Comment by griembauer** [comment]
In #11 the band info is now added if the grass version is >=7.9

**Comment by neteler** [comment]
Thanks for the fix!
